/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-05-17 10:40:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Navbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link href=\"//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./Styles/Homepage.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("#custom-search-input {\r\n");
      out.write("        margin:0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    #custom-search-input .search-query {\r\n");
      out.write("        padding-right: 3px;\r\n");
      out.write("        padding-right: 4px \\9;\r\n");
      out.write("        padding-left: 3px;\r\n");
      out.write("        padding-left: 4px \\9;\r\n");
      out.write("        /* IE7-8 doesn't have border-radius, so don't indent the padding */\r\n");
      out.write(" \r\n");
      out.write("        margin-bottom: 0;\r\n");
      out.write("        -webkit-border-radius: 3px;\r\n");
      out.write("        -moz-border-radius: 3px;\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    #custom-search-input button {\r\n");
      out.write("        border: 0;\r\n");
      out.write("        background: none;\r\n");
      out.write("        /** belows styles are working good */\r\n");
      out.write("        padding: 2px 5px;\r\n");
      out.write("        margin-top: 2px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        left: -28px;\r\n");
      out.write("        /* IE7-8 doesn't have border-radius, so don't indent the padding */\r\n");
      out.write("        margin-bottom: 0;\r\n");
      out.write("        -webkit-border-radius: 3px;\r\n");
      out.write("        -moz-border-radius: 3px;\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("        color:#D9230F;\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    .search-query:focus + button {\r\n");
      out.write("        z-index: 3;   \r\n");
      out.write("    }\r\n");
      out.write("   \t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("  <strong><a class=\"navbar-brand\" href=\"#\">GRIZZLY <img alt=\"logo\" src=\"./images/logo.png\" width=\"30px\" height=\"30px\"> STORE</a></strong>\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container container1\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("    <div class=\"col-lg-6\">\r\n");
      out.write("    <form>\r\n");
      out.write("       <div id=\"custom-search-input\">\r\n");
      out.write("         <div class=\"input-group col-md-12\">\r\n");
      out.write("         \t<input type=\"text\" class=\"  search-query form-control inp\" placeholder=\"Search\" />\r\n");
      out.write("            <span class=\"input-group-btn\">\r\n");
      out.write("\t            <button class=\"btn\" type=\"button\">\r\n");
      out.write("\t            <span class=\" glyphicon glyphicon-search\" style=\"color:#bdc3c7\" ></span>\r\n");
      out.write("\t            </button>\r\n");
      out.write("            </span>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div> \r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("       </div>\r\n");
      out.write("                     \r\n");
      out.write("    </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  <div  style=\"margin-top: 5px;margin-right: 30px;\">\r\n");
      out.write("       \t<i class=\"material-icons\">&#xe7f4;</i>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("      \r\n");
      out.write("   <div style=\"margin-top: 5px;margin-right: 40px;\">\r\n");
      out.write("   <h4 >Welcome\r\n");
      out.write("\t");

		out.print(session.getAttribute("username"));
	
      out.write("   \r\n");
      out.write("\t</h4>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t<div style=\"margin-right:30px;\">\r\n");
      out.write("\t<form action=\"LogoutController\" method=\"post\">\r\n");
      out.write("\t<button type=\"submit\" class=\"btn lgn_btn\" style=\"width:80px;\"><strong>Logout</strong></button>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write(" \r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
