/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-05-17 10:39:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class TabNav_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1557381648454L));
    _jspx_dependants.put("jar:file:/C:/Users/765697/Desktop/aswath-ws/eclipse-ws/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/grizzly-store-vendor-web-final-check/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function openCity(evt, cityName) {\r\n");
      out.write("    var i, tabcontent, tablinks;\r\n");
      out.write("    tabcontent = document.getElementsByClassName(\"tabcontent\");\r\n");
      out.write("    for (i = 0; i < tabcontent.length; i++) {\r\n");
      out.write("        tabcontent[i].style.display = \"none\";}\r\n");
      out.write("        \r\n");
      out.write("    tablinks = document.getElementsByClassName(\"tablinks\");\r\n");
      out.write("    for (i = 0; i < tablinks.length; i++) {\r\n");
      out.write("        tablinks[i].className = tablinks[i].className.replace(\" active\", \"\");}\r\n");
      out.write("\r\n");
      out.write("document.getElementById(cityName).style.display = \"block\";\r\n");
      out.write("    evt.currentTarget.className += \" active\";}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\t.inp\r\n");
      out.write("\t{\r\n");
      out.write("\t\tborder-radius: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.container1\r\n");
      out.write("\t{\r\n");
      out.write("\t\tmargin-top:0px;\r\n");
      out.write("\t\tmargin-left:10%;\r\n");
      out.write("\t\t\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.lgn_btn\r\n");
      out.write("\t{\r\n");
      out.write("\t\tmargin-rignt:30%;\r\n");
      out.write("\t\tborder-radius: 25px;\r\n");
      out.write("\t\tbackground:#bdc3c7;\r\n");
      out.write("\t}\t\r\n");
      out.write("\th4\r\n");
      out.write("\t{\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write(" \t.tab \r\n");
      out.write(" \t{\r\n");
      out.write(" \t\toverflow: hidden; border: 1px solid #ccc; \r\n");
      out.write("\t\tbackground-color: #f1f1f1;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.tabcontent \r\n");
      out.write("\t{\r\n");
      out.write("\t\tdisplay: none; padding: 6px 12px; border: 1px solid #ccc;\r\n");
      out.write("    \tborder-top: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\t.tab button \r\n");
      out.write("\t{\r\n");
      out.write("\t\tbackground-color: inherit; float: left; border: none;\r\n");
      out.write("    \toutline: none; cursor: pointer; padding: 14px 16px; \r\n");
      out.write("    \ttransition: 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\t.tab button:hover \r\n");
      out.write("\t{\r\n");
      out.write("\t\tbackground-color: #ddd;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.tab .active\r\n");
      out.write("\t {\r\n");
      out.write("\t \tbackground-color: #ccc;\r\n");
      out.write("\t }\r\n");
      out.write("\r\n");
      out.write("\t.tabcontent \r\n");
      out.write("\t{\r\n");
      out.write("\t\tdisplay: none; \r\n");
      out.write("\t\tpadding: 6px 12px;\r\n");
      out.write("\t\r\n");
      out.write("\t\tborder: 1px solid #ccc; \r\n");
      out.write("\t\tborder-top: none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\ttable \r\n");
      out.write("\t{\r\n");
      out.write("\t\tfont-family: arial, sans-serif; \r\n");
      out.write("\t\tborder-collapse: collapse;\r\n");
      out.write("    \twidth: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\ttd, th\r\n");
      out.write("\t{\r\n");
      out.write("\t\tborder: 1px solid ; padding: 8px; \r\n");
      out.write("    \ttext-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\t/*Change color to gray*/\r\n");
      out.write("\ttr:nth-child(even) {\r\n");
      out.write("    \tbackground-color: ;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\t.actived a{color:green}\r\n");
      out.write("\t.actived a:hover{ font-weight: bold}\r\n");
      out.write("\r\n");
      out.write("\t.deactivated a{color:red}\r\n");
      out.write("\t.deactivated a:hover{ font-weight: bold}\r\n");
      out.write("\r\n");
      out.write("\t.available {color:green; }\r\n");
      out.write("\t.disable{ color: red; font-weight: bold}\r\n");
      out.write("\t.intraining{color: blue; font-weight: bold}\r\n");
      out.write("\t.vacation{ font-weight: bold}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\" \" style=\"background-color:white; margin-top: 2%;margin-left: 2%\">\r\n");
      out.write("\t<div class=\"\">\r\n");
      out.write("\t\t<div class=\"tab\">\r\n");
      out.write("\t\t\t<button class=\"tablinks\" onclick=\"openCity(event, 'Products')\">PRODUCTS</button>\r\n");
      out.write("\t\t\t<button class=\"tablinks\" onclick=\"openCity(event, 'Inventory')\">INVENTORY</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"Products\" class=\"tabcontent\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"text\" placeholder=\"ChooseAction\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"text\" placeholder=\"productId/Product\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<select>\r\n");
      out.write("\t\t\t<option>name</option>\r\n");
      out.write("\t\t\t<option>id</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<button type=\"button\" onclick=\"openCity(event, 'AddProduct')\">Add Product</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t  \t\t<table>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th style=\"width:06%\">select</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th style=\"width:14%\">Product list</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th>Brand</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th>Category</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th>Rating</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th >Actions</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t  \t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"Inventory\" class=\"tabcontent\">\r\n");
      out.write("\t\t ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t <table>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th style=\"width:06%\">select</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th style=\"width:14%\">Product list</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th>availablity</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th>required</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th>price</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th>Rating</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t<th >Actions</th>\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t</tr>\r\n");
      out.write("\t\t \t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t \t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"AddProduct\" class=\"tabcontent\">\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"VendorController\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"text\" name=\"productid\"  placeholder=\"enter the product id\"><br><br>\r\n");
      out.write("\t\t<input type=\"text\" name=\"quantity\" placeholder=\"enter the quantity\"><br><br>\r\n");
      out.write("\t\t<button type=\"submit\" class=\"btn btn-success\" >Submit</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /TabNav.jsp(148,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty productlist}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /TabNav.jsp(158,11) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/TabNav.jsp(158,11) '${productlist}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${productlist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /TabNav.jsp(158,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("product");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t  \t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t  \t\t\t\t\t<td style=\"background-color: white\"></td>\r\n");
          out.write("\t\t\t\t\t\t  \t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t  \t\t\t\t\t<td style=\"background-color: white\"><a href=\"ViewProductController?pname=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write('	');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></td>\r\n");
          out.write("\t\t\t\t\t\t  \t\t\t\t\t<td style=\"background-color: white\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.brand}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t  \t\t\t\t\t<td style=\"background-color: white\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t  \t\t\t\t\t<td style=\"background-color: white\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.rating}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t  \t\t\t\t\t<td style=\"background-color: white\"> <button>view</button><button>block</button><button>Remove</button></td>\r\n");
          out.write("\t\t\t\t\t\t  \t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t  \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /TabNav.jsp(172,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty inventoryList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /TabNav.jsp(183,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/TabNav.jsp(183,4) '${inventoryList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${inventoryList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /TabNav.jsp(183,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("inventory");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t \t\t<tr>\r\n");
          out.write("\t\t \t\t<td style=\"background-color: white\"></td>\r\n");
          out.write("\t\t\t\t<td style=\"background-color: white\"><a href=\"\">\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inventory.productname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></td>\r\n");
          out.write("\t\t\t\t<td style=\"background-color: white\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inventory.availablity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t<td style=\"background-color: white\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inventory.required}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t<td style=\"background-color: white\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inventory.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t<td style=\"background-color: white\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inventory.rating}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t<td style=\"background-color: white\"> <button>view</button><button>block</button><button>Remove</button></td>\r\n");
          out.write("\t\t \t\t</tr>\r\n");
          out.write("\t\t \t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
